In [27]:
import pandas as pd
import numpy as np
import requests
import camelot
import logging

In [34]:
import pandas as pd
import numpy as np
import requests
import camelot
import logging


# Configuración de logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def descargar_pdf(url, ruta_archivo):
    """
    Descarga el archivo PDF desde la URL proporcionada.
    
    Args:
        url (str): URL del archivo PDF.
        ruta_archivo (str): Ruta donde se guardará el archivo PDF.
    
    Returns:
        bool: True si la descarga fue exitosa, False de lo contrario.
    """
    try:
        response = requests.get(url)
        response.raise_for_status()  # Verifica si la respuesta fue exitosa
        with open(ruta_archivo, "wb") as f:
            f.write(response.content)
        logging.info(f"Archivo PDF descargado correctamente en {ruta_archivo}")
        return True
    except requests.RequestException as e:
        logging.error(f"Error al descargar el archivo PDF: {e}")
        return False


def extraer_tablas_de_pdf(ruta_archivo, pages, row):
    """
    Extrae las tablas del archivo PDF utilizando camelot.
    
    Args:
        ruta_archivo (str): Ruta del archivo PDF.
        pages (str): Páginas a considerar.
        row (str): Filas a considerar.
    
    Returns:
        pd.DataFrame: DataFrame con las tablas extraídas.
    """
    try:
        tablas = camelot.read_pdf(ruta_archivo, flavor='stream', pages=pages, row=row)
        df_ingresos = pd.concat([tabla.df for tabla in tablas], ignore_index=True)
        logging.info(f"Tablas extraídas correctamente del archivo PDF")
        return df_ingresos
    except Exception as e:
        logging.error(f"Error al extraer las tablas del archivo PDF: {e}")
        return None


def main():
    url_pdf = "" # Agrega aquí la ruta donde se encuentra tu archivo PDF 
    ruta_archivo = "IngresosFeb22.pdf" # Selecciona un nombre para tu archivo PDF
    pages = "all"
    row = "7-end"

    if descargar_pdf(url_pdf, ruta_archivo):
        df_ingresos = extraer_tablas_de_pdf(ruta_archivo, pages, row)
        if df_ingresos is not None:
            logging.info(f"Resultado:")
            print(df_ingresos)
            df_ingresos.to_excel("IngresosFeb22.xlsx", index=False)
        else:
            logging.error(f"No se pudieron extraer las tablas del archivo PDF")
    else:
        logging.error(f"No se pudo descargar el archivo PDF")


if __name__ == "__main__":
    main()

2024-10-08 09:54:31,706 - INFO - Archivo PDF descargado correctamente en IngresosEne22.pdf
2024-10-08T09:54:32 - INFO - Processing page-1
2024-10-08 09:54:32,810 - INFO - Processing page-1
2024-10-08T09:54:33 - INFO - Processing page-2
2024-10-08 09:54:33,420 - INFO - Processing page-2
2024-10-08T09:54:34 - INFO - Processing page-3
2024-10-08 09:54:34,022 - INFO - Processing page-3
2024-10-08T09:54:34 - INFO - Processing page-4
2024-10-08 09:54:34,630 - INFO - Processing page-4
2024-10-08T09:54:35 - INFO - Processing page-5
2024-10-08 09:54:35,019 - INFO - Processing page-5
2024-10-08 09:54:35,093 - INFO - Tablas extraídas correctamente del archivo PDF
2024-10-08 09:54:35,094 - INFO - Resultado:

             0                                          1      2  \
0       CUENTA                                   CONCEPTO
1
2            1                 PT     INGRESOS CORRIENTES
3          1.1  PT     INGRESOS DE JURISDICCIÓN MUNICIPAL
4       1.1.01                PT     INGRESOS TRIBUTARIOS
..         ...                                        ...    ...
194  3.1.02.04       PI     OTRAS RETENCIONES AL PERSONAL
195     3.1.03              PT     OTRAS CUENTAS DE ORDEN
196  3.1.03.01              PI     OTRAS CUENTAS DE ORDEN
197  3.1.03.02           PI     RETENCIONES A PROVEEDORES
198                                                        TOTAL

                    3               4               5                 6  \
0       PRESUPUESTADO       RECAUDADO       RECAUDADO         RECAUDADO
1                          EN PERIODO       ACUMULADO          EN MENOS
2    1.966.042.800,00  124.499.337,11  255.103.944,91  1.729.871.320,75
3      902.789.000,00   73.206.169,62  126.489.300,91    787.042.966,10
4      682.411.000,00   67.192.774,43  106.402.823,37    586.751.443,64
..                ...             ...             ...               ...
194     65.000.000,00    1.214.183,53   18.373.609,18     46.626.390,82
195     11.000.000,00      660.110,59    1.504.870,87      9.495.129,13
196      5.000.000,00            0,00            0,00      5.000.000,00
197      6.000.000,00      660.110,59    1.504.870,87      4.495.129,13
198  2.624.685.800,00  128.328.154,75  519.905.066,74  2.180.025.447,27

                 7
0        RECAUDADO
1           EN MAS
2    18.932.465,66
3    10.743.267,01
4    10.743.267,01
..             ...
194           0,00
195           0,00
196           0,00
197           0,00
198  75.244.714,01

[199 rows x 8 columns]

In [2]:

def extraer_tablas_de_pdf(url):
    # Descargar el archivo PDF
    response = requests.get(url)
    with open("temp.pdf", "wb") as f:
        f.write(response.content)

    # Extraer tablas utilizando camelot con flavor='stream'
    tablas = camelot.read_pdf("temp.pdf", flavor='stream', pages='all', row="7-end")

    # Combinar tablas en un solo DataFrame
    df_combinado = pd.concat([tabla.df for tabla in tablas], ignore_index=True)

    return df_combinado

url_pdf = "http://datos.jesusmaria.gov.ar/dataset/66a6159b-88ce-46af-8a0b-793a48ed5f18/resource/da21ffc9-ef8b-4b32-9cc9-8edfed41b29b/download/ingresoenero2022.pdf"

df_combinado = extraer_tablas_de_pdf(url_pdf)

In [3]:
df_combinado

,0,1,2,3,4,5,6
0,Período: 01/01/2022 al 31/01/2022,,,,,,NaN
1,CUENTA,CONCEPTO,PRESUPUESTADO,RECAUDADO,PORCENTAJE,,NaN
2,,,,ACUMULADO,RECAUDADO,,NaN
3,1,PT INGRESOS CORRIENTES,"1.966.042.800,00","130.604.607,80","6,64",%,NaN
4,1.1,PT INGRESOS DE JURISDICCIÓN MUNICIPAL,"902.789.000,00","53.283.131,29","5,90",%,NaN
...,...,...,...,...,...,...,...
192,3.1.02.04,PI OTRAS RETENCIONES AL PERSONAL,,"65.000.000,00","17.159.425,65","26,40",%
193,3.1.03,PT OTRAS CUENTAS DE ORDEN,,"11.000.000,00","844.760,28","7,68",%
194,3.1.03.01,PI OTRAS CUENTAS DE ORDEN,,"5.000.000,00","0,00","0,00",%
195,3.1.03.02,PI RETENCIONES A PROVEEDORES,,"6.000.000,00","844.760,28","14,08",%
196,,,TOTALES,"2.624.685.800,00","391.576.911,99","14,92",%

In [4]:
df_combinado.drop([4, 5, 6], axis=1, inplace=True)

In [5]:
df_combinado.drop([0, 1, 2], inplace=True)

In [6]:
df_combinado

,0,1,2,3
3,1,PT INGRESOS CORRIENTES,"1.966.042.800,00","130.604.607,80"
4,1.1,PT INGRESOS DE JURISDICCIÓN MUNICIPAL,"902.789.000,00","53.283.131,29"
5,1.1.01,PT INGRESOS TRIBUTARIOS,"682.411.000,00","39.210.048,94"
6,1.1.01.01,PT TASA A LA PROPIEDAD INMUEBLE,"153.650.000,00","3.973.261,98"
7,1.1.01.01.01,PI TASA A LA PROPIEDAD INMUEBLE - EJERCICI...,"115.000.000,00","110.543,14"
...,...,...,...,...
192,3.1.02.04,PI OTRAS RETENCIONES AL PERSONAL,,"65.000.000,00"
193,3.1.03,PT OTRAS CUENTAS DE ORDEN,,"11.000.000,00"
194,3.1.03.01,PI OTRAS CUENTAS DE ORDEN,,"5.000.000,00"
195,3.1.03.02,PI RETENCIONES A PROVEEDORES,,"6.000.000,00"
196,,,TOTALES,"2.624.685.800,00"

In [7]:
df_combinado.rename(columns={0:"Cuenta", 1:"Concepto", 2:"Presupuestado", 3:"Recaudado Acumulado"}, inplace= True)

In [8]:
df_combinado

,Cuenta,Concepto,Presupuestado,Recaudado Acumulado
3,1,PT INGRESOS CORRIENTES,"1.966.042.800,00","130.604.607,80"
4,1.1,PT INGRESOS DE JURISDICCIÓN MUNICIPAL,"902.789.000,00","53.283.131,29"
5,1.1.01,PT INGRESOS TRIBUTARIOS,"682.411.000,00","39.210.048,94"
6,1.1.01.01,PT TASA A LA PROPIEDAD INMUEBLE,"153.650.000,00","3.973.261,98"
7,1.1.01.01.01,PI TASA A LA PROPIEDAD INMUEBLE - EJERCICI...,"115.000.000,00","110.543,14"
...,...,...,...,...
192,3.1.02.04,PI OTRAS RETENCIONES AL PERSONAL,,"65.000.000,00"
193,3.1.03,PT OTRAS CUENTAS DE ORDEN,,"11.000.000,00"
194,3.1.03.01,PI OTRAS CUENTAS DE ORDEN,,"5.000.000,00"
195,3.1.03.02,PI RETENCIONES A PROVEEDORES,,"6.000.000,00"
196,,,TOTALES,"2.624.685.800,00"

In [9]:
df_presupuesto_js = df_combinado.iloc[0:183]

In [10]:
df_presupuesto_js

,Cuenta,Concepto,Presupuestado,Recaudado Acumulado
3,1,PT INGRESOS CORRIENTES,"1.966.042.800,00","130.604.607,80"
4,1.1,PT INGRESOS DE JURISDICCIÓN MUNICIPAL,"902.789.000,00","53.283.131,29"
5,1.1.01,PT INGRESOS TRIBUTARIOS,"682.411.000,00","39.210.048,94"
6,1.1.01.01,PT TASA A LA PROPIEDAD INMUEBLE,"153.650.000,00","3.973.261,98"
7,1.1.01.01.01,PI TASA A LA PROPIEDAD INMUEBLE - EJERCICI...,"115.000.000,00","110.543,14"
...,...,...,...,...
181,3,PT NO CLASIFICADOS,"285.500.000,00","18.004.185,93"
182,3.1,PT CUENTAS DE ORDEN,"285.500.000,00","18.004.185,93"
183,3.1.01,PT POR TRABAJOS PÚBLICOS,"1.500.000,00","0,00"
184,3.1.01.01,PI FONDO DE REPARO,"1.000.000,00","0,00"
185,3.1.01.02,PI GARANTIA DE ADJUDICACION,"500.000,00","0,00"

In [11]:
df_presupuesto_js = df_presupuesto_js.reset_index(drop=True)

In [12]:
df_presupuesto_js

,Cuenta,Concepto,Presupuestado,Recaudado Acumulado
0,1,PT INGRESOS CORRIENTES,"1.966.042.800,00","130.604.607,80"
1,1.1,PT INGRESOS DE JURISDICCIÓN MUNICIPAL,"902.789.000,00","53.283.131,29"
2,1.1.01,PT INGRESOS TRIBUTARIOS,"682.411.000,00","39.210.048,94"
3,1.1.01.01,PT TASA A LA PROPIEDAD INMUEBLE,"153.650.000,00","3.973.261,98"
4,1.1.01.01.01,PI TASA A LA PROPIEDAD INMUEBLE - EJERCICI...,"115.000.000,00","110.543,14"
...,...,...,...,...
178,3,PT NO CLASIFICADOS,"285.500.000,00","18.004.185,93"
179,3.1,PT CUENTAS DE ORDEN,"285.500.000,00","18.004.185,93"
180,3.1.01,PT POR TRABAJOS PÚBLICOS,"1.500.000,00","0,00"
181,3.1.01.01,PI FONDO DE REPARO,"1.000.000,00","0,00"
182,3.1.01.02,PI GARANTIA DE ADJUDICACION,"500.000,00","0,00"

In [16]:
print(np.sum(df_presupuesto_js.isna()))

Cuenta                 0
Concepto               0
Presupuestado          0
Recaudado Acumulado    0
dtype: int64

In [20]:
print(np.sum(df_presupuesto_js.duplicated()))

4

In [22]:
df_presupuesto_js.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183 entries, 0 to 182
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Cuenta               183 non-null    object
 1   Concepto             183 non-null    object
 2   Presupuestado        183 non-null    object
 3   Recaudado Acumulado  183 non-null    object
dtypes: object(4)
memory usage: 5.8+ KB

In [25]:
df_presupuesto_js.to_excel("PresupuestoEnero22.xlsx", index=False)